classmates=['Michael','Bob','Tracy']
len(classmates)
classmates[0]
classmates[1]
classmates[2]
classmates[-1]
classmates[-2]
classmates[-3]
classmates.append('Adam')
classmates
classmates.insert(1,'Jack')
classmates
classmates.pop(1)
classmates
classmates[1]='Sarah'
classmates
L=['Apple',123,True]
s=['python','java',['asp','php'],'scheme']
len(s)
p=['asp','php']
s=['python','java',p,'scheme']
l=[]
len(l)

classmates=('Michael','Bob','Tracy')
classmates[0]
classmates[-1]
t=(1,2)
t
t=()
t
t=(1)
t
t=(1,)
t
t=('a','b',['A','B'])
t[2][0]='X'
t[2][1]='Y'
t
